CREATE TABLE IF NOT EXISTS sales (
    order_id TEXT PRIMARY KEY,
    order_date DATE,
    customer_id TEXT,
    customer_name TEXT,
    gender TEXT,
    age INTEGER,
    city TEXT,
    state TEXT,
    category TEXT,
    product_name TEXT,
    quantity INTEGER,
    unit_price REAL,
    discount_percent REAL,
    final_price REAL,
    cost_per_unit REAL,
    revenue REAL,
    cost REAL,
    profit REAL,
    payment_method TEXT,
    order_status TEXT,
    profit_margin REAL,
    year INTEGER,
    month INTEGER,
    month_name TEXT,
    year_month TEXT,
    customer_segment TEXT
);
